name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      R_BUILD_IGNORE_QUARTO: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::roxygen2
            any::rcmdcheck
          needs: check

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
          needs: check

      - name: Check
        run: |
          R CMD check --no-manual --as-cran .

      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: northwind.Rcheck/
